# Basic
title: zpc
subtitle: zpc's blog
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: zpc's blog.
creator: <a href="http://zpc.cn">@zpc</a>

url: "http://zpc.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: zpc, description: zpc, url: 'http://zpc.cn'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    #github: onevcat
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: wweun@vip.qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
